web/holidays/urls.py
from django.urls import path

from holidays.views.dashboard import dashboard
from holidays.views.holiday_event_create import holiday_event_create
from holidays.views.holiday_event_delete import holiday_event_delete
from holidays.views.holiday_event_list import holiday_event_list
from holidays.views.holiday_event_update import holiday_event_update
from holidays.views.holiday_ical_export import holiday_ical_export

urlpatterns = [
    path('', dashboard, name='holiday_dashboard'),

    path('event/<employment_id>', holiday_event_list, name='holiday_event_list'),
    path('event/<employment_id>/create', holiday_event_create, name='holiday_event_create'),
    path('event/<employment_id>/update/<pk>', holiday_event_update, name='holiday_event_update'),
    path('event/<employment_id>/delete/<pk>', holiday_event_delete, name='holiday_event_delete'),
    path('event/<int:holiday_event_id>/ical_export', holiday_ical_export, name="holiday_event_ical_export"),
]

web/statistic_module/urls.py
from django.urls import path

from statistic_module.views.company_statistics import CompanyIntervalStatistics
from statistic_module.views.statistic_intervals import interval_overview_and_export
from statistic_module.views.statistic_tokens import tokens_list_create, tokens_update_delete, token_detail_view

urlpatterns = [
	path('tokens', tokens_list_create, name="statistic_tokens_list_create"),
	path('tokens/<token_id>', tokens_update_delete, name="statistic_tokens_update_delete"),
	path('tokens/<token_id>/details', token_detail_view, name="statistic_token_detail_view"),
	path('interval_overview_and_export', interval_overview_and_export, name='interval_overview_and_export'),
	path('interval_overview_and_export/<token>', interval_overview_and_export, name='interval_overview_and_export_token'),
	path('company/<int:company_id>/interval_statistics', CompanyIntervalStatistics.as_view(), name="company_interval_statistics")
]

web/webTimesheets/urls.py
from django.contrib import admin
from django.views.generic import RedirectView
from django.urls import include, path

from management.views.impressum import impressum

urlpatterns = [
    path('', include('timesheets.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('prometheus/', include('django_prometheus.urls')),
    path('impressum/', impressum, name='impressum'),
    path('timesheets/', include('timesheets.urls')),
    path('holidays/', include('holidays.urls')),
    path('management/', include('management.urls')),
    path('stats/', include('statistic_module.urls')),
    path('sickness/', include('sickness.urls')),

    path('admin/', admin.site.urls, name="admin"),

    # re_path(r'^accounts/login(?P<path>.*)$', RedirectView.as_view(url='/')),
    path('accounts/', include('allauth.urls')),

    path('invitations/', include('invitations.urls', namespace='invitations')),
]

web/statistic_module/models.py
import uuid

from allauth.utils import build_absolute_uri
from django.contrib.postgres.fields import JSONField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _, gettext_lazy

from django.contrib.auth.models import User
from django.db import models


class ImplementedStatistics(models.TextChoices):
    INTERVALS = 'INT', _('Intervals')


class StatisticToken(models.Model):
    token = models.UUIDField(verbose_name=gettext_lazy("Token"), primary_key=True, editable=False, default=uuid.uuid4)
    user = models.ForeignKey(User, verbose_name=gettext_lazy("User"), on_delete=models.CASCADE)

    statistic = models.CharField(verbose_name=gettext_lazy("Statistic"), max_length=4,
                                 choices=ImplementedStatistics.choices)

    valid_from = models.DateField(verbose_name=gettext_lazy("Valid from"), null=True, blank=True)
    expire_at = models.DateField(verbose_name=gettext_lazy("Expire at"), null=True, blank=True)

    filter_data = models.JSONField(verbose_name=gettext_lazy("Filter data"), null=True, blank=True,
                                   help_text="Add defaults for forms that cannot be changed when using the access token.")

    def get_link(self, request=None):
        base_url = ''
        if self.statistic == ImplementedStatistics.INTERVALS:
            base_url = reverse('interval_overview_and_export')

        base_url += "/" + str(self.token)
        if request:
            base_url = build_absolute_uri(request, location=base_url)
        return base_url

    class Meta:
        verbose_name = gettext_lazy("Statistic Token")
        verbose_name_plural = gettext_lazy("Statistic Tokens")
        ordering = ["user", "valid_from"
                    ]


class TokenAccessLog(models.Model):
    datetime = models.DateTimeField(verbose_name=gettext_lazy("Datetime"), editable=False, auto_now_add=True)
    token = models.ForeignKey(StatisticToken, verbose_name=gettext_lazy("Token"), editable=False,
                              on_delete=models.CASCADE)
    request = models.JSONField(verbose_name=gettext_lazy("Request"), editable=False)

    class Meta:
        verbose_name = gettext_lazy("Token access log")
        verbose_name_plural = gettext_lazy("Token access logs")
        ordering = ["datetime"]

web/statistic_module/forms/statistic_token.py
from django import forms
from django.utils.translation import gettext_lazy

from statistic_module.models import ImplementedStatistics
from webTimesheets.custom_form_fields import DateInput


class StatisticTokenForm(forms.Form):
    statistic = forms.ChoiceField(
        label=gettext_lazy("Statistic"),
        choices=ImplementedStatistics.choices,
    )
    valid_from = forms.DateField(
        label=gettext_lazy("Valid from"),
        widget=DateInput(),
        required=False,
        input_formats=["%Y-%m-%d", "%d.%m.%Y"],
        help_text="2020-01-31 or 31.01.2020"
    )
    expire_at = forms.DateField(
        label=gettext_lazy("Expire at"),
        widget=DateInput(),
        required=False,
        input_formats=["%Y-%m-%d", "%d.%m.%Y"],
        help_text="2020-01-31 or 31.01.2020"
    )
    filter_data = forms.JSONField(
        label=gettext_lazy("Filter Data"),
        required=False,
    )

web/statistic_module/views/company_statistics.py
from _decimal import Decimal
from io import BytesIO

import structlog
import xlsxwriter
from django.contrib.auth.decorators import login_required
from django.db.models import Sum, F, Value, CharField, Q
from django.db.models.functions import Round, Trunc, Concat
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.template import loader
from django.utils.decorators import method_decorator
from django.views import View

from management.models import Company
from statistic_module.excel_exports.aggregated_statistic_cat_subcat import \
    aggregated_statistic_category_subcategory_excel_export
from statistic_module.excel_exports.aggregated_statistic_day_issue_urls import \
    aggregated_statistic_day_issue_url_excel_export
from statistic_module.excel_exports.aggregated_statistic_day_notes import aggregated_statistic_day_notes_excel_export
from statistic_module.forms.interval_filter import IntervalFilterCompanyStatisticForm
from statistic_module.helper import get_hourly_rate
from timesheets.models import Interval, Category, Subcategory
from timesheets.templatetags.nice_timedelta import decimal_hours
from timesheets.utils import daterange


@method_decorator(login_required, name='dispatch')
class CompanyIntervalStatistics(View):

    def get(self, request, company_id):
        '''
        calculate aggregate statistics based on filter
        category, subcategory, start_date, end_date
        '''
        template = loader.get_template('statistic_module/company_interval_statistics.html')
        context = {}

        company = get_object_or_404(
            Company,
            id=company_id
        )
        context["company"] = company

        form = IntervalFilterCompanyStatisticForm(data=request.GET, company=company)
        context["form"] = form

        return HttpResponse(template.render(context, request))

    def post(self, request, company_id):
        template = loader.get_template('statistic_module/company_interval_statistics.html')
        context = {}
        logger = structlog.getLogger("timesheets")
        company = get_object_or_404(
            Company,
            id=company_id
        )
        context["company"] = company

        form = IntervalFilterCompanyStatisticForm(data=request.POST, company=company)

        if form.is_valid():
            context["form"] = form
            filter_start = None
            filter_end = None
            filter_categories = None
            filter_subcategories = None
            filter_users = None
            filter_billable = None
            logger.info("CompanyIntervalStatistics", filter=form.cleaned_data)
            if "start" in form.cleaned_data and form.cleaned_data["start"]:
                filter_start = form.cleaned_data["start"]

            if "end" in form.cleaned_data and form.cleaned_data["end"]:
                filter_end = form.cleaned_data["end"]

            if "categories" in form.cleaned_data and form.cleaned_data["categories"]:
                filter_categories = form.cleaned_data["categories"]

            if "subcategories" in form.cleaned_data and form.cleaned_data["subcategories"]:
                filter_subcategories = form.cleaned_data["subcategories"]

            if "users" in form.cleaned_data and form.cleaned_data["users"]:
                filter_users = form.cleaned_data["users"]

            if "billable" in form.cleaned_data:
                filter_billable = form.cleaned_data["billable"]

            # relevant categories
            categories = Category.objects.filter(
                company=company,
                working_time=True,
            )
            if filter_categories:
                categories = categories.filter(
                    id__in=[c.pk for c in filter_categories]
                )

            # relevant subcategories
            subcategories = Subcategory.objects.filter(
                company=company
            )
            if filter_subcategories:
                subcategories = subcategories.filter(
                    id__in=[sc.pk for sc in filter_subcategories]
                )

            # relevant intervals
            intervals = Interval.objects.filter(
                category__in=categories,
                subcategory__in=subcategories
            )

            if filter_billable is not None:
                # if filter_billable = True, we filter for hourly_rate__isnull=False,
                # so we only look at non-null hourly rates thus filtering billable subcategories
                intervals = intervals.filter(
                    Q(category__hourly_rate__isnull=not filter_billable) |
                    Q(subcategory__hourly_rate__isnull=not filter_billable)

                )

            if filter_users:
                intervals = intervals.filter(
                    user__in=filter_users
                )

            if filter_start:
                intervals = intervals.filter(
                    start__date__gte=filter_start
                )
            if filter_end:
                intervals = intervals.filter(
                    start__date__lte=filter_end
                )

            category_statistics = []
            subcategory_statistics = []
            day_statistics = []
            financial_statistics = {}

            sum_amount = 0
            sum_price = Decimal(0)

            # category statistics
            for category in categories:
                cat_intervals = intervals.filter(
                    category=category
                )
                category_amount = 0
                category_price = Decimal(0)

                # subcategory statistics
                for subcategory in subcategories:
                    subcat_intervals = intervals.filter(
                        category=category,
                        subcategory=subcategory
                    )
                    subcategory_amount = 0
                    timedelta = subcat_intervals.aggregate(duration=Sum(F("end") - F("start")))["duration"]
                    if timedelta:
                        subcategory_amount = decimal_hours(timedelta)
                    category_amount += subcategory_amount
                    if subcategory_amount:
                        hourly_rate = get_hourly_rate(category, subcategory)
                        subcategory_price = Decimal(0)
                        if hourly_rate:
                            subcategory_price = Decimal(subcategory_amount) * hourly_rate
                            category_price += subcategory_price

                        subcategory_statistics.append(
                            {
                                "category": category,
                                "subcategory": subcategory,
                                "amount": subcategory_amount,
                                "price": subcategory_price
                            }
                        )

                timedelta = cat_intervals.aggregate(duration=Sum(F("end") - F("start")))["duration"]
                if timedelta:
                    amount = decimal_hours(timedelta)
                sum_amount += category_amount
                sum_price += category_price
                # category statistics
                if category_amount:
                    # category statistics
                    category_statistics.append(
                        {
                            "category": category,
                            "amount": category_amount,
                            "price": category_price,
                        }
                    )
            financial_statistics["sum_price"] = sum_price
            financial_statistics["sum_amount"] = sum_amount

            context["financial_statistics"] = financial_statistics

            detail_data = intervals \
                .values("user__username", "start__date", "category__name", "subcategory__name") \
                .annotate(username=F("user__username")) \
                .annotate(category_name=F("category__name")) \
                .annotate(subcategory_name=F("subcategory__name")) \
                .annotate(date=F("start__date")) \
                .annotate(duration=Sum(Trunc("end", "minute") - Trunc("start", "minute"))) \
                .values("username", "category_name", "subcategory_name", "date", "duration")

            context["detail_data"] = detail_data
            human_readable_name = f"{company.name}"
            if filter_start and filter_end:
                human_readable_name += f"_{filter_start.strftime('%Y-%m-%d')}-{filter_end.strftime('%Y-%m-%d')}"

            if request.POST['action'] == 'download_agg_cat_subcat':
                xlsx_data = aggregated_statistic_category_subcategory_excel_export(intervals, company.name)

                response = HttpResponse(
                    xlsx_data,
                    content_type='application/vnd.ms-excel'
                )
                response['Content-Disposition'] = 'attachment; filename=' + human_readable_name + '.xlsx'
                return response
            if request.POST['action'] == 'download_agg_day_issue_url':
                xlsx_data = aggregated_statistic_day_issue_url_excel_export(intervals, company.name)

                response = HttpResponse(
                    xlsx_data,
                    content_type='application/vnd.ms-excel'
                )
                response['Content-Disposition'] = 'attachment; filename=' + human_readable_name + '.xlsx'
                return response
            if request.POST['action'] == 'download_agg_day_notes':

                xlsx_data = aggregated_statistic_day_notes_excel_export(intervals, human_readable_name)

                response = HttpResponse(
                    xlsx_data,
                    content_type='application/vnd.ms-excel'
                )

web/statistic_module/templates/statistic_module/company_interval_statistics.html
{% extends 'tailwind-base.html' %}
{% load i18n %}
{% load nice_timedelta %}

{% block title %}{% blocktrans with name=company.name %}Statistics for <span class="font-bold">{{name}}</span>{% endblocktrans %}{% endblock %}

{% block content %}


    <div class="flex flex-col gap-12 ">
        <form  action="#" method="post">
            <div class="flex flex-col gap-2">
                {% csrf_token %}
                {% include 'tailwind-form-inline.html' with form=form %}
                <div>
                    <a href="{% url 'company_interval_statistics' company.id %}" class="btn btn-secondary">
                        {% trans "Reset" %}
                    </a>
                    <button type="submit" class="btn btn-primary" name="action" value="filter">{% trans "Filter" %}</button>
                    <button type="submit" class="btn btn-secondary" name="action" value="download_agg_cat_subcat">{% trans "Download Category Subcategory" %}</button>
                    <button type="submit" class="btn btn-secondary" name="action" value="download_agg_day_notes">{% trans "Download Day Notes" %}</button>
                    <button type="submit" class="btn btn-secondary" name="action" value="download_agg_day_issue_url">{% trans "Download Day Issue Url" %}</button>
                </div>

            </div>
        </form>

        {% if financial_statistics %}
            <table class="timesheetstable">
                <tr class="timesheetstable-row hover:bg-primarycolor-100">
                    <td>{% trans "Total hours" %}:</td>
                    <td class="text-right">{{ financial_statistics.sum_amount |floatformat:2}}</td>
                </tr>
                <tr class="timesheetstable-row hover:bg-primarycolor-100">
                    <td>{% trans "Total price" %}:</td>
                    <td class="text-right">{{ financial_statistics.sum_price |floatformat:2}}{{ currency }}</td>
                </tr>
            </table>

        {% endif %}
        {% if category_statistics %}
            <div>
             <canvas id="categoryStatisticsChart" class="max-w-xl" width="300" height="200"></canvas>
            </div>

             <table class="timesheetstable">
              <tr class="timesheetstable-header">
                <th>{% trans "Category" %}</th>
                <th class="text-right">{% trans "Amount" %}</th>
                <th class="text-right">{% trans "Price" %}</th>
              </tr>
              {% for category_data in category_statistics %}
              <tr class="timesheetstable-row hover:bg-primarycolor-100">
                <td>{{ category_data.category.name }}</td>
                <td class="text-right">{{ category_data.amount|floatformat:2}}</td>
                <td class="text-right">{% if category_data.price is not None %}{{ category_data.price|floatformat:2}}{{ currency }}{% endif %}</td>

              </tr>
              {% endfor %}
            </table>
        {% endif %}
        {% if subcategory_statistics %}
         <table class="timesheetstable">
          <tr class="timesheetstable-header">
            <th>{% trans "Category" %}</th>
            <th>{% trans "Subcategory" %}</th>
            <th class="text-right">{% trans "Amount" %}</th>
            <th class="text-right">{% trans "Price" %}</th>
          </tr>
          {% for subcategory_data in subcategory_statistics %}
          <tr class="timesheetstable-row hover:bg-primarycolor-100">
            <td>{{ subcategory_data.category.name }}</td>
            <td>{{ subcategory_data.subcategory.name }}</td>
            <td class="text-right">{{ subcategory_data.amount|floatformat:2}}</td>
            <td class="text-right">{% if subcategory_data.price is not None %}{{ subcategory_data.price|floatformat:2}}{{ currency }}{% endif %}</td>
          </tr>
          {% endfor %}
        </table>
        {% endif %}

    <div class="flex flex-col gap-2">
        <p class="text-sm text-gray-500">{% blocktrans %}Summary for each day, category and subcategory{% endblocktrans %}</p>
        <table class="timesheetstable">
            <tr class="timesheetstable-header">
                <th>{% trans 'Date' %}</th>
                <th>{% trans 'Category' %}</th>
                <th>{% trans 'Subcategory' %}</th>
                <th>{% trans 'Amount' %}</th>
            </tr>
     {% for r in detail_data %}
            <tr class="timesheetstable-row hover:bg-primarycolor-100">
                <td>{{ r.date |date:"Y-m-d" }}</td>
                <td>{{ r.category_name }}</td>
                <td>{{ r.subcategory_name }}</td>
                <td>{{ r.duration }}</td>
            </tr>
     {% endfor %}
    </table>
    </div>


    </div>

{% endblock %}


{%block scripts%}


<script>
// sumoselect


$(document).ready(function () {
  $('.selectCategories').SumoSelect({search: true, okCancelInMulti: true , csvDispCount:1 });
});
$(document).ready(function () {
  $('.selectSubcategories').SumoSelect({search: true, okCancelInMulti: true , csvDispCount:1 });
});
$(document).ready(function () {
  $('.selectUsers').SumoSelect({search: true, okCancelInMulti: true , csvDispCount:1 });
});

</script>

<script>
// jquery function
$(document).ready(function(){
    var ctx = document.getElementById('categoryStatisticsChart').getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'doughnut',
        data: {
            labels: [{%for data in category_statistics%}'{{data.category.name}}',{%endfor%}],
            datasets: [{
                label: '# of users',

                data: [{%for data in category_statistics%}{{data.amount|floatformat:0}},{% endfor %}],
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)',
                    'rgba(255, 99, 132, 0.1)',
                    'rgba(54, 162, 235, 0.1)',
                    'rgba(255, 206, 86, 0.1)',
                    'rgba(75, 192, 192, 0.1)',
                    'rgba(153, 102, 255, 0.1)',
                    'rgba(255, 159, 64, 0.1)'
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)',
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1,
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });
});
</script>
{%endblock scripts%}

web/statistic_module/templates/statistic_module/statistic_tokens_list_create.html
{% extends 'tailwind-base.html' %}
{% load i18n %}

{% load nice_timedelta %}

{% block title %}{% blocktrans %}Statistic Tokens{% endblocktrans %}{% endblock %}

{% block content %}

    {% if token_list %}
    <div class="my-14">
        <table class="timesheetstable">
          <tr class="timesheetstable-header">
            <th></th>
            <th>{% trans "Link" %}</th>
            <th>{% trans "Statistic" %}</th>
            <th>{% blocktrans %}Valid From{% endblocktrans %}</th>
            <th>{% blocktrans %}Expire at{% endblocktrans %}</th>
            <th>{% trans "Accesses" %}</th>
            <th>{% trans "Filter" %}</th>
          </tr>
          {% for entry in token_list %}
          <tr class="timesheetstable-row hover:bg-primarycolor-100">
            <td>
                <a href="{% url 'statistic_tokens_update_delete' entry.token.token %}" class="btn-secondary btn-inline">Edit</a></td>
            <td>
                <button id="{{ entry.token }}" class="btn-secondary btn-inline h-8 w-8" onclick="copyTextToClipboard('{{ entry.url }}', '{{ entry.token }}')">
                <svg xmlns="http://www.w3.org/2000/svg"  fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                </svg>
                </button>
            </td>
            <td>{{ entry.token.get_statistic_display }}</td>
            <td>{{ entry.token.valid_from }}</td>
            <td>{{ entry.token.expire_at }}</td>
            <td><a class="font-bold text-primarycolor-800" href="{% url 'statistic_token_detail_view' entry.token.token %}">{{ entry.accesses }}</a></td>
            <td>
                {% for key, value in entry.token.filter_data.items %}
                    <p><span class="font-bold">{{ key }}</span>: {{ value }}</p>
                {% endfor %}
            </td>
          </tr>

          {% endfor %}
        </table>
    </div>
    {% else %}
        <p>{% blocktrans %}There are no tokens, create a new one now{% endblocktrans %}</p>
    {% endif %}
<div class="my-14">
    <h2 class="text-xl font-bold my-2">{% blocktrans %}Create a Token{% endblocktrans %}</h2>

    <form action="#" method="post">{% csrf_token %}
        {% include "tailwind-form.html" %}

        <div class="my-6 flex flex-row gap-4">
            <button class="btn btn-primary" type="submit">{% trans "Create" %}</button>
        </div>


    </form>
</div>

    <div class="my-14">
        <h3 class="text-lg font-bold my-2">{% blocktrans %}Example Filter Data{% endblocktrans %}</h3>
        <p>{% trans "Intervals" %}</p>
        <pre><code>
{"start": "2020-01-01", "end": "2020-12-31", "category": ["CategoryName"], "subcategory": ["SubcategoryName1", "SubcategoryName2"]}
        </code></pre>
    </div>
<script>

function setToPing(id){
    var button = document.getElementById(id);
    button.classList.add('animate-ping');
}

function stopPing(id){
    var button = document.getElementById(id);
    button.classList.remove('animate-ping');
}

function copyTextToClipboard( text, id ) {
  /* Get the text field */
  navigator.clipboard.writeText(text)
    .then(() => {
      if (id != null){
        setToPing(id);
        setTimeout(function(){ stopPing(id); }, 1000);
      }
    })
    .catch(err => {
      alert('Error in copying text: ', err);
    });
}
</script>
{% endblock %}

web/statistic_module/templates/statistic_module/statistic_tokens_update_delete.html
{% extends 'tailwind-base.html' %}
{% load i18n %}

{% load nice_timedelta %}

{% block title %}{% blocktrans %}Statistic Token{% endblocktrans %}{% endblock %}

{% block content %}
<form action="#" method="post">{% csrf_token %}
    {% include "tailwind-form.html" %}

    <div class="my-6 flex flex-row gap-4">
        <button class="btn btn-primary" type="submit" name="save">{% trans "Save" %}</button>
        <button class="btn btn-secondary" onclick="goBack()">{% trans "Go Back" %}</button>
        <div class="contents m-0 p-0">
            <span class="group flex flex-row items-baseline gap-x-2">
                <span class=" text-red-700 btn" >{% trans "Delete" %}</span>
                <button class="btn btn-danger hidden group-hover:block group-focus:block " type="submit" name="delete">{% blocktrans %}Really delete!{% endblocktrans %}</button>
            </span>
        </div>

    </div>


</form>

<script>
function goBack() {
  window.history.back();
}
</script>
{% endblock %}

web/statistic_module/templates/statistic_module/token_detail.html
{% extends 'tailwind-base.html' %}
{% load i18n %}

{% load nice_timedelta %}

{% block title %}{% blocktrans with token=statistic_token.token %}Token {{ statistic_token.token }}{% endblocktrans %}{% endblock %}

{% block content %}

<h2 class="text-xl font-bold mt-6 mb-1">{% blocktrans %}Requests using this token{% endblocktrans %}</h2>

<table class="timesheetstable">
    <tr class="timesheetstable-header">
        <th>{% trans "Datetime" %}</th>
        <th>{% blocktrans %}Client IP{% endblocktrans %}</th>
        <th>{% trans "Method" %}</th>
        <th>{% blocktrans %}User Agent{% endblocktrans %}</th>
        <th>{% trans "Path" %}</th>
        <th>{% trans "Content" %}</th>
    </tr>
    {% for log in access_logs %}
        <tr class="timesheetstable-row hover:bg-primarycolor-100">
            <td>{{ log.datetime }}</td>
            <td>{{ log.request.client_ip }}</td>
            <td>{{ log.request.method }}</td>
            <td>{{ log.request.user_agent }}</td>
            <td>{{ log.request.path }}</td>
            <td>
                {% if log.request.method == "GET" %}
                    {{ log.request.get }}
                {% elif log.request.method == "POST" %}
                    {{ log.request.post }}
                {% endif %}
            </td>
        </tr>
    {% endfor %}
</table>

{% endblock %}